name       : libsigsegv
version    : '2.15'
release    : 5
source     :
    - https://ftpmirror.gnu.org/gnu/libsigsegv/libsigsegv-2.15.tar.gz : 036855660225cb3817a190fc00e6764ce7836051bacb48d35e26444b8c1729d9
homepage   : https://www.gnu.org/software/libsigsegv/
license    : GPL-2.0-or-later
component  : programming.tools
summary    : GNU libsigsegv is a library for handling page faults in user mode.
description: |
    GNU libsigsegv is a library for handling page faults in user mode. A page fault occurs when a program tries to access to a region of memory that is currently not available.
setup      : |
    %reconfigure --enable-shared --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
