# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : breeze-gtk-theme
version    : 6.6.3
release    : 141
source     :
    - https://download.kde.org/stable/plasma/6.6.3/breeze-gtk-6.6.3.tar.xz : 32e2e5947d5d26c1ae2020feca79302d2eea54bce655a6596dd34df5656e5e8d
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt6Core)
    - breeze-devel
    - extra-cmake-modules
    - python-cairo
    - sassc
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
