# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : extra-cmake-modules
version    : 6.25.0
release    : 107
source     :
    - https://download.kde.org/stable/frameworks/6.25/extra-cmake-modules-6.25.0.tar.xz : ffeb4951bf09b2b8ee17ef24a28b6de650c0db0f59ddffb9009b37cac63af348
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - CC0-1.0
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5/KF6.
description: |
    Extra cmake modules and scripts for KF5/KF6.
builddeps  :
    - pkgconfig(Qt6Designer)
    - doxygen
    - python-sphinx
    - python-sphinxcontrib-qthelp
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_kf6 -DBUILD_QTHELP_DOCS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
    rm -rfv $installdir/usr/share/doc/ECM/html
