# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kdecoration
version    : 6.6.4
release    : 136
source     :
    - https://download.kde.org/stable/plasma/6.6.4/kdecoration-6.6.4.tar.xz : 20d9424a018fabbf62987bc138741068ae2384f3128a61f23d906ff4f42a5505
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - CC0-1.0
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
