name       : font-lato-ttf
version    : 2.015
release    : 6
source     :
    - https://sources.getsol.us/Lato2OFL.zip : 42b54e96c07e299d967fc3227c7bd63a20d6cfb1dc8fd6dae83628091e20a5b8
    # Direct download not possible. Download manually and upload to server.
    #- https://www.latofonts.com/download/Lato2OFL.zip : 42b54e96c07e299d967fc3227c7bd63a20d6cfb1dc8fd6dae83628091e20a5b8
homepage   : https://www.latofonts.com
license    : OFL-1.1
component  : desktop.font
summary    : A sanserif typeface family
description: |
    Lato is a sanserif typeface family designed in the summer 2010 by Warsaw-​​based designer Łukasz Dziedzic ("Lato" means "Summer" in Polish).
install    : |
    mkdir -p $installdir/usr/share/fonts/truetype
    mkdir -p $installdir/usr/share/fonts/conf.d

    install -dm 00755 $installdir/usr/share/fonts/truetype/lato
    install -pm 00644 *.ttf $installdir/usr/share/fonts/truetype/lato
    install -Dm 00644 $pkgfiles/lato-fontconfig.conf $installdir/usr/share/fontconfig/conf.avail/69-lato.conf

    ln -s /usr/share/fontconfig/conf.avail/69-lato.conf $installdir/usr/share/fonts/conf.d/69-lato.conf

    install -Dm 00644 $pkgfiles/lato.metainfo.xml $installdir/usr/share/metainfo/lato.metainfo.xml
