# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kcalendarcore
version    : 6.25.0
release    : 35
source     :
    - https://download.kde.org/stable/frameworks/6.25/kcalendarcore-6.25.0.tar.xz : d6a19c3ec0cdfc6979bfde08ce7c62db8c52dd9dff4a13e4da8978e00480dfeb
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-3.0-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(libical)
    - extra-cmake-modules
    - qt6-base-private-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - libical-devel
        - qt6-tools-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
