name       : gnugo
version    : '3.8'
release    : 5
source     :
    - http://ftpmirror.gnu.org/gnu/gnugo/gnugo-3.8.tar.gz : da68d7a65f44dcf6ce6e4e630b6f6dd9897249d34425920bfdd4e07ff1866a72
homepage   : https://www.gnu.org/software/gnugo/
license    : GPL-3.0-or-later
component  : games.strategy
summary    : GNU Go is a free program that plays the game of Go.
description: |
    GNU Go is a free program that plays the game of Go.
environment: |
    export CFLAGS="${CFLAGS} -fcommon" # gcc10
setup      : |
    %configure_no_runstatedir
build      : |
    %make
install    : |
    %make_install
