# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-user-docs
version    : '49.5'
release    : 38
source     :
    - https://download.gnome.org/sources/gnome-user-docs/49/gnome-user-docs-49.5.tar.xz : 8a6efb2fc9b48375e643d2df6e6925379f73c87e5b5198f34badb1c6e5850cc3
homepage   : https://gitlab.gnome.org/GNOME/gnome-user-docs
license    : CC-BY-3.0
component  : desktop.gnome.doc
summary    : GNOME core documentation
description: |
    This package contains documents which will be packaged together and shipped as gnome-user-docs in the core GNOME distribution. They should be documents targeted for end-users of GNOME and have general GNOME applicability.
builddeps  :
    - pkgconfig(yelp-xsl)
    - itstool
    - yelp-tools
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
