name       : gdu
version    : 5.31.0
release    : 1
source     :
    - https://github.com/dundee/gdu/archive/refs/tags/v5.31.0/gdu-5.31.0.tar.gz : e3727680ea346ce86e63d4c97841cbc5e17c6d8e58fac8b8e9886e3339214e9d
homepage   : https://github.com/dundee/gdu
license    : MIT
component  : system.utils
summary    : Pretty fast disk usage analyzer written in Go.
description: |
    Gdu is intended primarily for SSD disks where it can fully utilize parallel processing. However HDDs work as well, but the performance gain is not so huge.
networking : true
builddeps  :
    - git
    - golang
build      : |
    BUILD_USER="Solus"
    go build \
        -buildmode=pie \
        -ldflags="-s -w -linkmode external \
        -X 'github.com/dundee/gdu/v5/build.Version=$version' \
        -X 'github.com/dundee/gdu/v5/build.User=$BUILD_USER'" \
        -o gdu \
        ./cmd/gdu
install    : |
    install -Dm00755 gdu $installdir/usr/bin/gdu
    install -Dm00644 gdu.1 $installdir/usr/share/man/man1/gdu.1