name       : gettext
version    : '0.26'
release    : 21
source     :
    - https://ftpmirror.gnu.org/gnu/gettext/gettext-0.26.tar.gz : 39acf4b0371e9b110b60005562aace5b3631fed9b1bb9ecccfc7f56e58bb1d7f
homepage   : https://www.gnu.org/software/gettext
license    : GPL-3.0-or-later
component  : system.base
summary    : Localisation support for programs
description: |
    The Gettext package contains utilities for internationalization and localization. These allow programs to be compiled with NLS (Native Language Support), enabling them to output messages in the user's native language.
autodep    : false
libsplit   : false
builddeps  :
    - pkgconfig(libattr)
    - pkgconfig(libpcre)
patterns   :
    - docs : /usr/share/doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
