name       : polylith
version    : 0.3.30
homepage   : https://polylith.gitbook.io/polylith/
release    : 6
source     :
    - https://github.com/polyfy/polylith/archive/refs/tags/v0.3.30.tar.gz : 02946a125af110621515a93c5293efbdb84229ecfcd743c598f40e069d203e64
license    : EPL-1.0
component  : programming.tools
networking : true
summary    : Clojure tool for managing polylith projects
description: |
    The poly tool helps you manage your polylith projects which introduces the architectural concept of "service level building blocks" which can be combined like LEGO® bricks to build our services and systems.
environment: |
    export JAVA_CMD=/usr/lib64/openjdk-17/bin/java
    export JAVA_HOME=/usr/lib64/openjdk-17
    export PATH=$JAVA_HOME/bin:$PATH
builddeps  :
    - clojure-tools
rundeps    :
    - openjdk-17
build      : |
    clojure -T:build uberjar :project poly
install    : |
    install -Dm00755 $pkgfiles/poly $installdir/usr/bin/poly
    install -Dm00644 ./projects/poly/target/poly.jar $installdir/usr/lib/polylith/poly.jar
