# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kidletime
version    : 6.25.0
release    : 33
source     :
    - https://download.kde.org/stable/frameworks/6.25/kidletime-6.25.0.tar.xz : 64e83d46a15b444017c6341e479e229bbd6cbb8320ef1359773737cee89dd7ca
homepage   : https://community.kde.org/Frameworks
license    :
    - CC0-1.0
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MIT
component  : desktop.library
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
builddeps  :
    - pkgconfig(Qt6DBus)
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(Qt6Widgets)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
    - plasma-wayland-protocols-devel
    - qt6-base-private-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-base-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
