name       : mtools
version    : 4.0.49
release    : 13
source     :
    - https://ftpmirror.gnu.org/gnu/mtools/mtools-4.0.49.tar.gz : 10cd1111da87bf2400a380c1639a6cba8bfb937a24f9c51f5f88d393ae5f6f76
license    : GPL-3.0-or-later
homepage   : https://www.gnu.org/software/mtools/
component  : system.utils
summary    : A collection of utilities to access MS-DOS disks without mounting them
description: |
    Mtools is a collection of utilities to access MS-DOS disks from GNU and Unix without mounting them. It supports Win'95 style long file names, OS/2 Xdf disks and 2m disks (store up to 1992k on a high density 3 1/2 disk). In addition to file access, it supports many FAT-specific features: volume labels, FAT-specific file attributes (hidden, system, ...), "bad block" map maintenance, access to remote floppy drives, Iomega ZIP disk protection, "secure" erase, display of file's on-disk layout, etc.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install -j1
