# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : proj
version    : 9.8.0
release    : 10
source     :
    - https://github.com/OSGeo/PROJ/releases/download/9.8.0/proj-9.8.0.tar.gz : a8b493b00cf4d08b712b9e063ed5e53e2be90fcde46770e9dbd773341f378f43
homepage   : https://proj.org/
license    : MIT
component  : programming.library
summary    : PROJ - Cartographic Projections and Coordinate Transformations Library. (Previously known as proj.4)
description: |
    PROJ is a generic coordinate transformation software, that transforms coordinates from one coordinate reference system (CRS) to another. This includes cartographic projections as well as geodetic transformations.
builddeps  :
    - pkgconfig(gtest)
    - pkgconfig(libcurl)
    - pkgconfig(libtiff-4)
    - pkgconfig(sqlite3)
replaces   :
    - proj.4
    - devel : proj.4-devel
    - dbginfo : proj.4-dbginfo
setup      : |
    %cmake_ninja -DUSE_EXTERNAL_GTEST=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -fr $installdir/usr/share/doc/
    %install_license COPYING
check      : |
    %ninja_check || :
