name       : pspp
version    : 2.0.1
release    : 13
source     :
    - https://ftpmirror.gnu.org/gnu/pspp/pspp-2.0.1.tar.gz : 8edbb0f09e8cf8010cad9e0559e0230d7fc5aae4721c756c350554df33024c00
homepage   : https://www.gnu.org/software/pspp/
license    : GPL-3.0-or-later
component  : office.maths
summary    : Statistical analysis program
description: |
    A free and open source alternative to the proprietary (and expensive) statistical analysis software, SPSS, by IBM. Published by the Free Software Foundation.
builddeps  :
    - pkgconfig(gsl)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(libpng)
    - pkgconfig(spread-sheet-widget)
    - gettext-devel
setup      : |
    # See http://savannah.gnu.org/bugs/?65892, remove all .png related docs
    %patch -p1 -i $pkgfiles/disable-png.patch

    # FIXME: reconfigure macro doesn't pick up -I
    autoreconf -vfi -I /usr/share/gettext/m4
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
