# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kicad-symbols
version    : 9.0.8
release    : 20
source     :
    - https://gitlab.com/kicad/libraries/kicad-symbols/-/archive/9.0.8/kicad-symbols-9.0.8.tar.gz : 0383fa9a3b141974f65316a587e2d417799bbbfb52cf9465c25f12412f2ff1e3
homepage   : https://www.kicad.org/
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad schematic symbol libraries
description: |
    Official KiCad schematic symbol libraries.
setup      : |
    %cmake
install    : |
    %make_install
    %install_license LICENSE.md
