name       : starship
version    : 1.24.0
release    : 25
source     :
    - https://github.com/starship/starship/archive/refs/tags/v1.24.0.tar.gz : 3d98e2c57dcfea36c6035e2ad812f91cfe33099e4b67f6ea7728e2294f02ca61
homepage   : https://starship.rs/
license    : ISC
component  : system.utils
networking : true
summary    : The minimal, blazing-fast, and infinitely customizable prompt for any shell!
description: |
    Works on the most common shells on the most common operating systems. Use it everywhere!

    Brings the best-in-class speed and safety of Rust, to make your prompt as quick and reliable as possible.

    Every little detail is customizable to your liking, to make this prompt as minimal or feature-rich as you'd like it to be.
builddeps  :
    - rust
checkdeps  :
    - git
setup      : |
    cp $pkgfiles/aeryn-os.toml docs/public/presets/toml/aeryn-os.toml

    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install

    # Install completions
    install -dm00755 $installdir/usr/share/bash-completion/completions
    install -dm00755 $installdir/usr/share/zsh/site-functions
    install -dm00755 $installdir/usr/share/fish/vendor_completions.d

    target/release/starship completions bash > $installdir/usr/share/bash-completion/completions/starship.bash
    target/release/starship completions zsh > $installdir/usr/share/zsh/site-functions/_starship
    target/release/starship completions fish > $installdir/usr/share/fish/vendor_completions.d/starship.fish

    # Default initialization
    install -Dm00644 $pkgfiles/50-starship.sh $installdir/usr/share/defaults/etc/profile.d/50-starship.sh
check      : |
    export TERM=xterm-256color
    %cargo_test -- --skip "modules::username::tests::show_always_false"
