name       : vivaldi-snapshot
version    : 7.7.3850.3
release    : 529
source     :
    - https://downloads.vivaldi.com/snapshot/vivaldi-snapshot_7.7.3850.3-1_amd64.deb : f964f6e6e32d766e8ea9935e7b6fa65a8119da6c116debc12fee786d0ba64b00
license    : Distributable
homepage   : https://vivaldi.com
component  : network.web.browser
summary    : Vivaldi Web Browser (Snapshot)
description: |
    An advanced browser made with the power user in mind.
strip      : false
extract    : false
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt6Core)
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - at-spi2-devel
    - ffmpeg-chromium
rundeps    :
    - ffmpeg-chromium
setup      : |
    ar xf $sources/vivaldi-snapshot_${version}-1_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
install    : |
    # This only excludes /usr/bin link which will be invalid
    install -D -d -m 00755 $installdir/usr/bin
    install -D -d -m 00644 $installdir/usr/share
    cp -R root/usr/share/applications $installdir/usr/share/

    # Fix metainfo
    install -Dm00644 root/usr/share/appdata/vivaldi-snapshot.appdata.xml $installdir/usr/share/metainfo/vivaldi-snapshot.metainfo.xml
    sed -i 's|vivaldi-snapshot-snapshot.desktop|vivaldi-snapshot.desktop|g' $installdir/usr/share/metainfo/vivaldi-snapshot.metainfo.xml
    sed -i 's|<translation/>||g' $installdir/usr/share/metainfo/vivaldi-snapshot.metainfo.xml

    # We do not use /opt for binary packages in Solus, so just use /usr/share.
    cp -R root/opt/* $installdir/usr/share/.
    ln -sv /usr/share/vivaldi-snapshot/vivaldi-snapshot $installdir/usr/bin/vivaldi-snapshot

    # Ensure we symlink to expected directory as expected file.
    # See https://gist.github.com/ruario/55a6671b155fe1da35a8d8a5b2352008
    majMin=$(echo '%version%' | cut -c-3)
    ln -s /usr/share/vivaldi-snapshot/libffmpeg.so $installdir/usr/share/vivaldi-snapshot/libffmpeg.so.${majMin}

    for icon_size in 16 24 32 48 64 128 256; do
        install -D -m 00644 root/opt/vivaldi-snapshot/product_logo_${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/vivaldi-snapshot.png
    done
