# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : oxygen-sounds
version    : 6.6.3
release    : 43
source     :
    - https://download.kde.org/stable/plasma/6.6.3/oxygen-sounds-6.6.3.tar.xz : c53b95557e318f78b26ee5bde1152781f61dfc1a441336dfa32ce8de5aee5be4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-2-Clause
    - CC0-1.0
    - CC-BY-3.0
    - LGPL-3.0-or-later
component  : desktop.theme
summary    : The Oxygen Sound Theme
description: The Oxygen Sound Theme
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
