# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : chezmoi
version    : 2.70.2
release    : 22
source     :
    - https://github.com/twpayne/chezmoi/archive/refs/tags/v2.70.2.tar.gz : 4dfacb37e1f6714305d7c8570bc25880342dfddbe81259c9253a5881de035321
homepage   : https://www.chezmoi.io
license    : MIT
component  : programming.tools
summary    : chezmoi helps you manage your personal configuration files across multiple machines
description: |
    chezmoi helps you manage your personal configuration files across multiple machines
networking : true
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
    %install_license LICENSE
