# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : rclone
version    : 1.73.5
release    : 46
source     :
    - https://github.com/rclone/rclone/archive/refs/tags/v1.73.5.tar.gz : e52541bc238dd434a0335f467697d7d9575529698a74aab534ad39b8649f8a49
license    : MIT
component  : network.util
homepage   : https://rclone.org
networking : true
summary    : Sync files to and from Google Drive, S3, Swift, Cloudfiles, etc.
description: |
    Sync files to and from Google Drive, S3, Swift, Cloudfiles, Dropbox and Google Cloud Storage
builddeps  :
    - golang
setup      : |
    %patch -p1 -i $pkgfiles/01-fix-version-from-archive-sources.patch
build      : |
    %make
    ./rclone genautocomplete bash rclone.bash_completion
    ./rclone genautocomplete fish rclone.fish_completion
    ./rclone genautocomplete zsh rclone.zsh_completion
install    : |
    install -Dm00755 rclone -t $installdir/usr/bin
    install -Dm00644 rclone.1 -t $installdir/usr/share/man/man1
    install -Dm00644 MANUAL.* -t $installdir/usr/share/doc/rclone
    install -Dm00644 rclone.bash_completion $installdir/usr/share/bash-completion/completions/rclone
    install -Dm00644 rclone.fish_completion $installdir/usr/share/fish/vendor_completions.d/rclone.fish
    install -Dm00644 rclone.zsh_completion $installdir/usr/share/zsh/site-functions/_rclone
