name       : gnuchess
version    : 6.3.0
release    : 12
source     :
    - https://ftpmirror.gnu.org/gnu/chess/gnuchess-6.3.0.tar.gz : 0b37bec2098c2ad695b7443e5d7944dc6dc8284f8d01fcc30bdb94dd033ca23a
homepage   : https://www.gnu.org/software/chess/
license    : GPL-3.0-or-later
component  : games.strategy
summary    : GNU Chess program
description: |
    GNU Chess lets most modern computers play a full game of chess. It has a terminal interface but supports visual interfaces such as XBoard.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
