# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kwindowsystem
version    : 6.25.0
release    : 37
source     :
    - https://download.kde.org/stable/frameworks/6.25/kwindowsystem-6.25.0.tar.xz : b51448a7669efa18190ab7fa8d6f5e0f77d8f9879cf457dadb4629b245a02434
homepage   : https://community.kde.org/Frameworks
license    :
    - CC0-1.0
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - LGPL-3.0-only
    - MIT
component  : programming.library
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xfixes)
    - extra-cmake-modules
    - plasma-wayland-protocols-devel
    - qt6-base-private-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - libx11-devel
        - qt6-tools-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
