# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libpng
version    : 1.6.56
release    : 35
source     :
    - https://sourceforge.net/projects/libpng/files/libpng16/1.6.56/libpng-1.6.56.tar.gz : 8f91e941a07fb1069ebb3855278f82a849e6af14ca05821e14ec3d5348697ea5
homepage   : https://www.libpng.org/pub/png/
license    : Libpng
component  : multimedia.library
summary    : libpng (Official PNG reference library)
description: |
    libpng is the official PNG reference library, supporting almost all PNG features and has been extensively tested.
emul32     : true
avx2       : true
builddeps  :
    - pkgconfig32(zlib)
setup      : |
    # Fails due to zlib-ng compression stream changes
    %patch -p1 -i $pkgfiles/0001-skip-pngtest-all.patch

    %configure --disable-static --enable-intel-sse
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/%libdir%/*.la
    %install_license LICENSE
check      : |
    %make check || ( cat ./test-suite.log && exit 1 )
patterns   :
    - devel :
        - /usr/bin/libpng*-config
