# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : aurorae
version    : 6.6.4
release    : 13
source     :
    - https://download.kde.org/stable/plasma/6.6.4/aurorae-6.6.4.tar.xz : f7dbc82de06a53dd2c3ff54ae542351485cd5b27e071fada5bb7fc87911054f3
homepage   : https://kde.org/plasma-desktop/
license    :
    - CC0-1.0
    - GPL-2.0-or-later
    - MIT
component  : programming.library
summary    : Themable window decorations for KWin
description: |
    Themable window decorations for KWin
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6UiTools)
    - extra-cmake-modules
    - kdecoration-devel
    - kf6-kcmutils-devel
    - kf6-kcolorscheme-devel
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - kf6-knewstuff-devel
    - kf6-kpackage-devel
    - kf6-ksvg-devel
rundeps    :
    - kf6-ksvg
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
