# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kwallet-pam
version    : 6.6.3
release    : 140
source     :
    - https://download.kde.org/stable/plasma/6.6.3/kwallet-pam-6.6.3.tar.xz : 965a008d89a64f8161673c6a32c7f71c28473ee2714856743b949acf18296e16
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(libgcrypt)
    - extra-cmake-modules
    - kf6-kwallet-devel
    - socat
rundeps    :
    - socat
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
