# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kwallet-pam
version    : 6.6.4
release    : 141
source     :
    - https://download.kde.org/stable/plasma/6.6.4/kwallet-pam-6.6.4.tar.xz : 731def95656f55114e6a5084e4ca722e2e9499d43fb613f4ca401904a47573e7
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(libgcrypt)
    - extra-cmake-modules
    - kf6-kwallet-devel
    - socat
rundeps    :
    - socat
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
