name       : dust
version    : 1.2.3
release    : 1
source     :
    - https://github.com/bootandy/dust/archive/refs/tags/v1.2.3.tar.gz : 424b26adfbafeac31da269ecb3f189eca09803e60fad90b3ff692cf52e0aeeee
homepage   : https://github.com/bootandy/dust
license    : Apache-2.0
component  : system.utils
summary    : A more intuitive version of du in rust
description: |
    A more intuitive version of du in rust
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install
    install -Dm0644 man-page/dust.1 $installdir/usr/share/man/man1/dust.1
    install -Dm0644 completions/dust.bash $installdir/usr/share/bash-completion/completions/dust
    install -Dm0644 completions/_dust $installdir/usr/share/zsh/site-functions/_dust
    install -Dm0644 completions/dust.fish $installdir/usr/share/fish/vendor_completions.d/dust.fish
