name       : global
version    : 6.6.14
release    : 8
source     :
    - https://ftpmirror.gnu.org/global/global-6.6.14.tar.gz : f6e7fd0b68aed292e85bb686616baf6551d5c9424adcddca11d808ba318cb320
homepage   : https://www.gnu.org/software/global/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : GNU GLOBAL is a source code tagging system that works the same way across diverse environments
description: |
    GNU GLOBAL is a source code tagging system that works the same way across diverse environments, such as Emacs editor, Vi editor, Less viewer, Bash shell, various web browsers, etc.
environment: |
    export CFLAGS="${CFLAGS} -Wno-incompatible-pointer-types"
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var
    install -D -m 0644 $pkgfiles/gtags.tmpfiles $installdir/%libdir%/tmpfiles.d/gtags.conf
