# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-workspace-wallpapers
version    : 6.6.3
release    : 45
source     :
    - https://download.kde.org/stable/plasma/6.6.3/plasma-workspace-wallpapers-6.6.3.tar.xz : 73854af7129707a75f8b131edfd42c440410b8f219babb6173314a22cce915dd
homepage   : https://kde.org/plasma-desktop
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : desktop.kde
summary    : Wallpapers for Plasma Workspaces
description: |
    Wallpapers for Plasma Workspaces
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING COPYING.LGPL3
