name       : uv
version    : 0.9.6
release    : 3
source     :
    - https://github.com/astral-sh/uv/archive/refs/tags/0.9.6.tar.gz : c32470f9f1c2903304fa6538fea3f153a9995a7f26da8024f4617bf1ad042936
homepage   : https://docs.astral.sh/uv
license    :
    - Apache-2.0
    - MIT
component  : programming.tools
summary    : An extremely fast Python package and project manager, written in Rust.
description: |
    An extremely fast Python package and project manager, written in Rust.
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build --bin uv --bin uvx

    # Build completions
    mkdir completions
    COMPGEN="target/release/uv --generate-shell-completion"
    $COMPGEN bash > "completions/$package.bash"
    $COMPGEN fish > "completions/$package.fish"
    $COMPGEN zsh > "completions/_$package"
install    : |
    %cargo_install uv uvx

    # Add license file and readme
    install -Dm0644 -t "$installdir/usr/share/licenses/$package/" LICENSE-* 
    install -Dm0644 -t "$installdir/usr/share/doc/$package/" README.md

    # Install completions
    install -Dm0644 "completions/$package.bash" -t "$installdir/usr/share/bash-completion/completions/"
    install -Dm0644 "completions/$package.fish" -t "$installdir/usr/share/fish/vendor_completions.d/"
    install -Dm0644 "completions/_$package" -t "$installdir/usr/share/zsh/site-functions/"
check      : |
    # Run smoke tests
    "$installdir/usr/bin/uv" run "$workdir/scripts/smoke-test"
