name       : unrtf
version    : 0.21.10
release    : 3
source     :
    - https://ftpmirror.gnu.org/gnu/unrtf/unrtf-0.21.10.tar.gz : b49f20211fa69fff97d42d6e782a62d7e2da670b064951f14bbff968c93734ae
homepage   : https://www.gnu.org/software/unrtf/
license    : GPL-3.0-only
component  : office.viewers
summary    : convert RTF documents to HTML, LaTeX, troff macros
description: |
    UnRTF is a command-line program written in C which converts documents in Rich Text Format (.rtf) to HTML, LaTeX, troff macros, and RTF itself. Converting to HTML, it supports a number of features of Rich Text
setup      : |
    %patch -p1 -i $pkgfiles/0001-Adjust-malloc-types.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
