# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : solseek
version    : 1.2.9
release    : 29
source     :
    - https://github.com/clintre/solseek/archive/refs/tags/v1.2.9.tar.gz : 9ac0125b3bba32bb44dee53fbad1630a14545776b5a39b70b2f204ad38e31028
homepage   : https://github.com/clintre/solseek
license    : GPL-3.0-or-later
component  : system.utils
summary    : A TUI Package Manager for Solus
description: |
    Solseek is a simple terminal user interface that allows you to browse, search, and manage packages from the Solus packages.
rundeps    :
    - appstream
    - font-firacode-nerd
    - fzf
    - packagekit
    - python3
install    : |-
    install -Dm00755 $workdir/package/bin/solseek $installdir/usr/bin/solseek
    install -dm00755 $installdir/usr/share
    cp -r $workdir/package/share/solseek $installdir/usr/share/
    chmod 00755 $installdir/usr/share/solseek/helpers/eopkg-info.py
    install -Dm00644 $workdir/package/share/applications/Solseek.desktop $installdir/usr/share/applications/Solseek.desktop
    install -Dm00644 $workdir/package/share/icons/hicolor/scalable/apps/solseek.svg $installdir/usr/share/icons/hicolor/scalable/apps/solseek.svg
    install -Dm00644 $workdir/package/share/metainfo/solseek.metainfo.xml $installdir/usr/share/metainfo/solseek.metainfo.xml
    %install_license LICENSE
