name       : libcdio-paranoia
version    : 10.2.2.0.2
release    : 9
source     :
    - https://github.com/libcdio/libcdio-paranoia/releases/download/release-10.2%2B2.0.2/libcdio-paranoia-10.2+2.0.2.tar.bz2 : 186892539dedd661276014d71318c8c8f97ecb1250a86625256abd4defbf0d0c
homepage   : https://www.gnu.org/software/libcdio/
license    : GPL-3.0-or-later
component  : multimedia.library
summary    : CD paranoia libraries from libcdi
description: |
    CD paranoia libraries from libcdi
builddeps  :
    - pkgconfig(libcdio)
setup      : |
    %configure --disable-static \
               --disable-example-progs \
               --enable-cpp-progs
build      : |
    %make
install    : |
    %make_install
    ln -s cd-paranoia $installdir/usr/bin/cdparanoia
check      : |
    %make check
