name       : libffcall
version    : '2.5'
release    : 4
homepage   : https://www.gnu.org/software/libffcall/
source     :
    - https://ftpmirror.gnu.org/gnu/libffcall/libffcall-2.5.tar.gz : 7f422096b40498b1389093955825f141bb67ed6014249d884009463dc7846879
license    : GPL-2.0-or-later
component  : programming.tools
summary    : GNU libffcall is a library which can be used to build foreign function call interfaces in embedded interpreters.
description: |
    It consists of two parts:
    - avcall: Calling C functions with variable arguments. Its include file is <avcall.h>.
    - callback: Closures with variable arguments as first-class C functions. Its include file is <callback.h>.
setup      : |
    %configure --disable-static
build      : |
    %make -j1
install    : |
    %make_install
check      : |
    %make check
