# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : hunspell-uk
version    : 6.7.5
release    : 14
source     :
    - https://github.com/brown-uk/dict_uk/releases/download/v6.7.5/hunspell-uk_UA_6.7.5.zip : 80fc8fed7f8e4b43c32fd2b7d2587f1c82184fa4d8e36d077370a1c802dcbe1e
homepage   : https://github.com/brown-uk/dict_uk/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : office.spelling
summary    : Ukrainian hunspell dictionary
description: |
    Ukrainian spelling dictionary for hunspell.
install    : |
    install -Dm00644 uk_UA.{aff,dic} -t $installdir/usr/share/hunspell
