# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : btrfs-progs
version    : 6.19.1
release    : 77
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v6.19.1.tar.xz : bb27e1ec54e7c3c0b7b2e596f853a73c07a3d72f21bc94042073c24dbf045796
license    : GPL-2.0-only
homepage   : https://btrfs.wiki.kernel.org/index.php/Main_Page
summary    :
    - Utilities for managing btrfs filesystems
    - libbtrfs : Library for managing btrfs filesystems
component  :
    - system.utils
    - libbtrfs : system.base
description:
    - Utilities for managing btrfs filesystems
    - libbtrfs : Library for managing btrfs filesystems
patterns   :
    - libbtrfs :
        - /usr/lib64/libbtrfs.so.*
        - /usr/lib64/libbtrfsutil.so.*
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libeconf)
    - pkgconfig(libzstd)
    - pkgconfig(lzo2)
    - pkgconfig(python3)
    - pkgconfig(reiserfscore)
    - asciidoc
    - python-sphinx
    - python-sphinx-rtd-theme
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
