name       : libidn2
version    : 2.3.8
release    : 13
source     :
    - https://ftpmirror.gnu.org/gnu/libidn/libidn2-2.3.8.tar.gz : f557911bf6171621e1f72ff35f5b1825bb35b52ed45325dcdee931e5d3c0787a
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : system.base
homepage   : https://www.gnu.org/software/libidn/#libidn2
summary    : Internationalized domain name support library
description: |
    Libidn2 is a free software implementation of IDNA2008, Punycode and TR46. Its purpose is to encode and decode internationalized domain names.
emul32     : true
builddeps  :
    - pkgconfig(gtk-doc)
    - libunistring-32bit-devel
patterns   :
    - docs : /usr/share/info
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
