# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-keyboard
version    : 6.6.3
release    : 3
source     :
    - https://download.kde.org/stable/plasma/6.6.3/plasma-keyboard-6.6.3.tar.xz : fd10bafeb13b1065720dbf8ee334354f050979eddec8b2b025f76c6eb1a1193c
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - CC0-1.0
    - FSFAP
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - GPL-3.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.kde
summary    : Virtual keyboard for Plasma
description: |
    Virtual keyboard for Plasma
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6VirtualKeyboard)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(wayland-protocols)
    - extra-cmake-modules
    - kf6-kcmutils-devel
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-ki18n-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    %install_license LICENSES/*
