# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : hugo
version    : 0.160.1
release    : 218
source     :
    - https://github.com/gohugoio/hugo/archive/refs/tags/v0.160.1.tar.gz : aaab9991fcc691aba35f8702c3cec65e2ba074408de70a9f66f7b868c28b8cdf
license    : Apache-2.0
homepage   : https://gohugo.io
component  : programming
networking : true
extract    : false
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
builddeps  :
    - golang
setup      : |
    mkdir -p src/github.com/gohugoio/hugo
    tar xf $sources/v${version}.tar.gz -C src/github.com/gohugoio/hugo --strip-components 1
build      : |
    cd ..
    export GO111MODULE=on
    export GOPATH=`pwd`
    export PATH=$PATH:$GOPATH:$GOPATH/bin/
    cd src/github.com/gohugoio/hugo
    go build -tags extended
install    : |
    cd src/github.com/gohugoio/hugo/
    install -Dm00755 hugo $installdir/usr/bin/hugo
    %install_license LICENSE
