name       : gperf
version    : '3.3'
release    : 6
source     :
    - https://ftpmirror.gnu.org/gnu/gperf/gperf-3.3.tar.gz : fd87e0aba7e43ae054837afd6cd4db03a3f2693deb3619085e6ed9d8d9604ad8
homepage   : https://www.gnu.org/software/gperf/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Gperf generates a perfect hash function from a key set
description: |
    Gperf generates a perfect hash function from a key set.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
