name       : arm-none-eabi-binutils
version    : '2.41'
release    : 6
source     :
    - https://ftpmirror.gnu.org/gnu/binutils/binutils-2.41.tar.xz : ae9a5789e23459e59606e6714723f2d3ffc31c03174191ef0d015bdf06007450
homepage   : https://www.gnu.org/software/binutils/
license    : GPL-3.0-or-later
summary    : The GNU Embedded Binutils for Arm
component  : programming
description: |
    A set of programs to assemble and manipulate binary and object files for the ARM EABI (bare-metal) target
environment: |
    export TARGET=arm-none-eabi
    export PREFIX=/usr/share/$TARGET
setup      : |
    %patch -p1 -i $pkgfiles/0001-Include-string.patch
    ./configure \
        --build=%HOST% \
        --target=$TARGET \
        --prefix=$PREFIX \
        --enable-multilib \
        --enable-interwork \
        --with-gnu-as \
        --with-gnu-ld \
        --disable-nls \
        --enable-ld=default \
        --enable-gold \
        --enable-plugins \
        --enable-deterministic-archives
build      : |
    %make
install    : |
    %make_install

    # Remove unnecessary files
    rm -rf $installdir$PREFIX/share

    # Install profile.d script which adds arm toolchain to path
    install -D -m 00644 $pkgfiles/50-arm-toolchain-path.sh $installdir/usr/share/defaults/etc/profile.d/50-arm-toolchain-path.sh
