# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kicad-packages3d
version    : 9.0.8
release    : 19
source     :
    - https://gitlab.com/kicad/libraries/kicad-packages3D/-/archive/9.0.8/kicad-packages3D-9.0.8.tar.gz : 227a807c0ef6d041350e23ae7e1680eb460f9177245e918fb07a32dff1bd51fa
homepage   : https://www.kicad.org/
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad 3D model libraries for rendering and MCAD integration
description: |
    Contains 3D models for rendering and MCAD integration, for use with KiCAD EDA software. The model needs a mechanical model source (a manually-modelled or script-generated file); its WRL counterpart file must be obtained as a conversion from the MCAD model.
setup      : |
    %cmake
install    : |
    %make_install
    %install_license LICENSE.md
