# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xreader
version    : 4.6.3
release    : 8
source     :
    - https://github.com/linuxmint/xreader/archive/refs/tags/4.6.3.tar.gz : fefcee0ea9810b4039e5150145a126545c731ab47cc7bad76c04cde139ed5a71
homepage   : https://github.com/linuxmint/xreader
license    : GPL-2.0-or-later
component  : office.viewers
summary    : A generic Document Reader
description: |
    Xreader is a document viewer capable of displaying multiple and single page document formats like PDF and Postscript.
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnomekbdui)
    - pkgconfig(libgxps)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(poppler-glib)
    - pkgconfig(sm)
    - pkgconfig(webkit2gtk-4.1)
    - pkgconfig(xapp)
    - pkgconfig(xkbfile)
    - pkgconfig(zlib)
    - itstool
    - mathjax2
    - yelp-tools
setup      : |
    %meson_configure \
        -Ddjvu=true \
        -Dpixbuf=true \
        -Dcomics=true \
        -Dintrospection=true \
        -Dhelp_files=true \
        -Dmathjax-directory=/usr/share/mathjax2
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
