# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kparts
version    : 6.25.0
release    : 31
source     :
    - https://download.kde.org/stable/frameworks/6.25/kparts-6.25.0.tar.xz : f0d6346e3127d1e44506733113be467d8b50cb82731d300a57990dd09baaedf1
homepage   : https://community.kde.org/Frameworks
license    :
    - CC0-1.0
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-only
component  : desktop.library
summary    : Plugin framework for user interface components
description: |
    Plugin framework for user interface components
builddeps  :
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-ktextwidgets-devel
    - kf6-kxmlgui-devel
    - kf6-sonnet-devel
rundeps    :
    - devel :
        - kf6-kio-devel
        - kf6-kservice-devel
        - kf6-kxmlgui-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
patterns   :
    - devel :
        - /usr/share/kdevappwizard
