# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : typos
version    : 1.45.0
release    : 3
source     :
    - https://github.com/crate-ci/typos/archive/refs/tags/v1.45.0.tar.gz : f7bd2b353818b4e6a2710c30b11f9d4ec62672d6f0c0f7186f6e84140f290d2a
license    :
    - Apache-2.0
    - MIT
component  : programming.tools
homepage   : https://github.com/crate-ci/typos
summary    : Source code spell checker
description: |
    Source code spell checker
builddeps  :
    - rust
checkdeps  :
    - rust-devel # Needs rustfmt
networking : true
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install
    %install_license LICENSE-APACHE
    %install_license LICENSE-MIT
check      : |
    %cargo_test
