name       : libunistring
version    : 1.4.1
release    : 11
source     :
    - https://ftpmirror.gnu.org/gnu/libunistring/libunistring-1.4.1.tar.xz : 67d88430892527861903788868c77802a217b0959990f7449f2976126a307763
homepage   : https://www.gnu.org/software/libunistring
license    : LGPL-3.0-or-later
component  : system.base
summary    : Library for manipulating Unicode strings
description: |
    libunistring is a GNU library that provides functions for manipulating Unicdoe strings and for manipulating C strings according to the Unicode standard.
emul32     : true
clang      : true
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
patterns   :
    - docs :
        - /usr/share/doc/*
