# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lagrange
version    : 1.20.1
release    : 28
source     :
    - https://github.com/skyjake/lagrange/releases/download/v1.20.1/lagrange-1.20.1.tar.gz : cd5f37f0db5790d9e02bd15b251998d28e8520985fcfc3b6dc54e3c975cdb970
homepage   : https://gmi.skyjake.fi/lagrange/
license    : BSD-2-Clause
component  : network.clients
summary    : A Beautiful Gemini and Gopher client
description: |
    Lagrange is a desktop GUI client for browsing Geminispace and Gopherspace. It offers modern conveniences familiar from web browsers, such as smooth scrolling, inline image viewing, multiple tabs, visual themes, Unicode fonts, bookmarks, history, gempub support, split view and page outlines.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(libwebp)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - libunistring-devel
rundeps    :
    - mpg123
setup      : |
    pushd $workdir/lib/the_Foundation
    %patch -p1 -i $pkgfiles/fix-build-for-glibc-2.43.patch
    popd
    %cmake_ninja -DTFDN_ENABLE_SSE41=No
build      : |
    %ninja_build
install    : |
    %ninja_install
