# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lagrange
version    : 1.20.2
release    : 29
source     :
    - https://github.com/skyjake/lagrange/releases/download/v1.20.2/lagrange-1.20.2.tar.gz : a1660e5a5b9e3149c53a4f544e5ac195c28f512fddbb61c8be135ac05ea65d12
homepage   : https://gmi.skyjake.fi/lagrange/
license    : BSD-2-Clause
component  : network.clients
summary    : A Beautiful Gemini and Gopher client
description: |
    Lagrange is a desktop GUI client for browsing Geminispace and Gopherspace. It offers modern conveniences familiar from web browsers, such as smooth scrolling, inline image viewing, multiple tabs, visual themes, Unicode fonts, bookmarks, history, gempub support, split view and page outlines.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(libwebp)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - libunistring-devel
rundeps    :
    - mpg123
setup      : |
    %cmake_ninja -DTFDN_ENABLE_SSE41=No
build      : |
    %ninja_build
install    : |
    %ninja_install
