# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libzim
version    : 9.5.1
release    : 17
source     :
    - https://github.com/openzim/libzim/archive/refs/tags/9.5.1.tar.gz : 5f4ac87887b05a6eaa408b4f03d3486262c8a5c13e488024822b293cdefe8c0e
homepage   : https://wiki.openzim.org/wiki/Libzim
license    : GPL-2.0-or-later
component  : programming.library
summary    : Reference implementation of the ZIM specification
description: |
    The Libzim is the reference implementation for the ZIM file format. It's a software library to read and write ZIM files on many systems and architectures. More information about the ZIM format and the openZIM project at https://openzim.org/.
builddeps  :
    - pkgconfig(gtest)
    - pkgconfig(icu-io)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - pkgconfig(uuid)
    - pkgconfig(xapian-core)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
