# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-attica
version    : 6.25.0
release    : 32
source     :
    - https://download.kde.org/stable/frameworks/6.25/attica-6.25.0.tar.xz : fa39cc74cd34ffd4beb906099a5f42e4180432b5839a75a4b251c0ae2fb01ab1
homepage   : https://community.kde.org/Frameworks
license    :
    - CC0-1.0
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.library
summary    : Open Collaboration Service client library.
description: |
    Open Collaboration Service client library.
builddeps  :
    - pkgconfig(Qt6Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-tools-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
