# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ksshaskpass
version    : 6.6.4
release    : 137
source     :
    - https://download.kde.org/stable/plasma/6.6.4/ksshaskpass-6.6.4.tar.xz : 46f3606c1591986091d9b289c491512e8c058216a71f20ccdcad32d5b02a4393
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - CC0-1.0
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
builddeps  :
    - kf6-kcoreaddons-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-kwallet-devel
    - kf6-kwidgetsaddons-devel
    - qt6-base-private-devel
    - qtkeychain-qt6-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
