name       : libidn
version    : '1.43'
release    : 12
source     :
    - https://ftpmirror.gnu.org/gnu/libidn/libidn-1.43.tar.gz : bdc662c12d041b2539d0e638f3a6e741130cdb33a644ef3496963a443482d164
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : network.library
homepage   : https://www.gnu.org/software/libidn
summary    : Internationalized domain name support library
description: |
    GNU library implementing Stringprep, Punycode and IDNA specifications.
emul32     : true
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
