# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : hunspell-da
version    : 2.8.232
release    : 5
source     :
    - https://stavekontrolden.dk/dictionaries/da_DK/da_DK-2.8.232.oxt : 08bea9b2a46286eaf99c91acea9755ef884bd1703eeeaeec80dcb38dccfdae9b
homepage   : https://www.stavekontrolden.dk/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : office.spelling
extract    : false
summary    : Danish hunspell dictionary
description: |
    Danish dictionary from Stavekontrolden / Danske ordbog til stavekontrol fra Stavekontrolden.
setup      : |
    unzip $sources/da_DK-2.8.232.oxt
install    : |
    install -Dm00644 da_DK.{aff,dic} -t $installdir/usr/share/hunspell
