# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : appstream-catalog
version    : '20260327'
release    : 49
source     :
    - https://appstream.getsol.us/data/unstable/main/Components-x86_64.xml.gz: 0879962b9c7eaf4111c730838651e4e5676e9392c7efdec715db1d5ccc5f5381
    - https://appstream.getsol.us/data/unstable/main/icons-128x128.tar.gz: 506660db74f081460c597cdf9f5cd8b8e3c3e363f7cc3e753e07c1f407152763
    - https://appstream.getsol.us/data/unstable/main/icons-128x128@2.tar.gz: cfebee1f9d89d02082aa64b907ab5c4614dc92cc7d2f739d620cc61f4846b972
    - https://appstream.getsol.us/data/unstable/main/icons-48x48.tar.gz: 99415826c93827ce11e037eeb2efdfb7944d3b6e63fca332a5ca6f7e701fa0f0
    - https://appstream.getsol.us/data/unstable/main/icons-48x48@2.tar.gz: 88769127dc2ae40511ed9a8146beae536e1a39de83bcee6884acf208eda1b1ba
    - https://appstream.getsol.us/data/unstable/main/icons-64x64.tar.gz: 5bb194b096bb6e538d88e378623b50067118b6c090c2445487ea20a0f9986b4f
    - https://appstream.getsol.us/data/unstable/main/icons-64x64@2.tar.gz: 9868435523e7213959a80ca21243ad07939100f05af92a94f11938951cfabe1a
homepage   : https://www.freedesktop.org/wiki/Distributions/AppStream/
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.3
component  : desktop.core
summary    : AppStream data for Solus
description: |
    AppStream data for Solus
extract    : false
install    : |
    install -Dm00644 $sources/Components-x86_64.xml.gz $installdir/usr/share/swcatalog/xml/solus-unstable-main.xml.gz

    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128@2

    tar xf $sources/icons-48x48.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48
    tar xf $sources/icons-48x48@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    tar xf $sources/icons-64x64.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64
    tar xf $sources/icons-64x64@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    tar xf $sources/icons-128x128.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128
    tar xf $sources/icons-128x128@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128@2
replaces   : appstream-data
