# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : appstream-catalog
version    : '20260320'
release    : 48
source     :
    - https://appstream.getsol.us/data/unstable/main/Components-x86_64.xml.gz: 9c2c8e608616983932155dce7b70715b751463126b14d5474f45788c8c47fab2
    - https://appstream.getsol.us/data/unstable/main/icons-128x128.tar.gz: 58813c927359b6c2f98f715c6c039601fea63b9aadf505314d2af3e388c6ba8b
    - https://appstream.getsol.us/data/unstable/main/icons-128x128@2.tar.gz: e3afd09e85b60cb58bd6d8db9d49430ffaf229b7ab6c469ff04fb8fead56cb16
    - https://appstream.getsol.us/data/unstable/main/icons-48x48.tar.gz: dd8624d14f7619f5314d694ae2bf42ecfb88930bcc7dafd28c0310a0b1ad16d2
    - https://appstream.getsol.us/data/unstable/main/icons-48x48@2.tar.gz: 39b0070eef437f46590bf2cfb2b2cfb663e659cde2cf21c0fcc49c1b6fa565bf
    - https://appstream.getsol.us/data/unstable/main/icons-64x64.tar.gz: 502d85d9752c1f414074d7ddd1f90fe0ba9c0a319319f8cb22ee6f9fa27e4c51
    - https://appstream.getsol.us/data/unstable/main/icons-64x64@2.tar.gz: a8061ca0e576b888cfaa6688dfeaf0388e723594fca26f7c23b8a215a7e5fb6e
homepage   : https://www.freedesktop.org/wiki/Distributions/AppStream/
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.3
component  : desktop.core
summary    : AppStream data for Solus
description: |
    AppStream data for Solus
extract    : false
install    : |
    install -Dm00644 $sources/Components-x86_64.xml.gz $installdir/usr/share/swcatalog/xml/solus-unstable-main.xml.gz

    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128@2

    tar xf $sources/icons-48x48.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48
    tar xf $sources/icons-48x48@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    tar xf $sources/icons-64x64.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64
    tar xf $sources/icons-64x64@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    tar xf $sources/icons-128x128.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128
    tar xf $sources/icons-128x128@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128@2
replaces   : appstream-data
