# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kf6-kuserfeedback
version    : 6.25.0
release    : 38
source     :
    - https://download.kde.org/stable/frameworks/6.25/kuserfeedback-6.25.0.tar.xz : 4ce9fd672bed20ce646cd175522d207e0fe753fe42c5cf773c087927c0f30fe3
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - CC0-1.0
    - MIT
component  : desktop.library
summary    : Framework for collecting user feedback for applications via telemetry and surveys
description: |
    Framework for collecting user feedback for applications via telemetry and surveys
builddeps  :
    - pkgconfig(Qt6Charts)
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6Svg)
    - extra-cmake-modules
    - php-devel
    - qt6-base-private-devel
rundeps    :
    - devel :
        - qt6-base-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6 -DBUILD_TESTING=OFF \
               -DENABLE_CONSOLE=ON \
               -DENABLE_CLI=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
