name       : mpd
version    : 0.24.5
release    : 99
source     :
    - https://github.com/MusicPlayerDaemon/MPD/archive/refs/tags/v0.24.5.tar.gz : ab7f9a2315eff97cc47dff5da9b9c675b1764cd50f161dc295b8a0d1956a6244
homepage   : https://www.musicpd.org
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : MPD is a flexible, powerful, server-side application for playing music
description: |
    Music Player Daemon (MPD) is a flexible, powerful, server-side application for playing music. Through plugins and libraries it can play a variety of sound files while being controlled by its network protocol.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(ao)
    - pkgconfig(audiofile)
    - pkgconfig(avahi-client)
    - pkgconfig(bzip2)
    - pkgconfig(faad2)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(fmt)
    - pkgconfig(icu-io)
    - pkgconfig(id3tag)
    - pkgconfig(jack)
    - pkgconfig(libavcodec)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libchromaprint)
    - pkgconfig(libcurl)
    - pkgconfig(libgcrypt)
    - pkgconfig(libmikmod)
    - pkgconfig(libmms)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpdclient)
    - pkgconfig(libmpg123)
    - pkgconfig(libnfs)
    - pkgconfig(libopenmpt)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(libupnp)
    - pkgconfig(liburing)
    - pkgconfig(mad)
    - pkgconfig(nlohmann_json)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(shout)
    - pkgconfig(smbclient)
    - pkgconfig(sndio)
    - pkgconfig(soxr)
    - pkgconfig(sqlite3)
    - pkgconfig(wavpack)
    - pkgconfig(wildmidi)
    - pkgconfig(zziplib)
    - lame-devel
    - libboost-devel
checkdeps  :
    - pkgconfig(cppunit)
setup      : |
    %patch -p1 -i $pkgfiles/mpd-sndfile.patch
    %meson_configure \
        -D io_uring=disabled  # liburing support broken: https://github.com/MusicPlayerDaemon/MPD/issues/2241
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 doc/mpdconf.example $installdir/usr/share/doc/mpd/mpd.conf
check      : |
    %ninja_check
